// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package app is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	AppReq
	AppResp
*/
package app

import (
	"fmt"
	"math"

	"github.com/golang/protobuf/proto"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppReq struct {
	Hello string `protobuf:"bytes,1,opt,name=hello" json:"hello,omitempty"`
}

func (m *AppReq) Reset()                    { *m = AppReq{} }
func (m *AppReq) String() string            { return proto.CompactTextString(m) }
func (*AppReq) ProtoMessage()               {}
func (*AppReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppReq) GetHello() string {
	if m != nil {
		return m.Hello
	}
	return ""
}

type AppResp struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *AppResp) Reset()                    { *m = AppResp{} }
func (m *AppResp) String() string            { return proto.CompactTextString(m) }
func (*AppResp) ProtoMessage()               {}
func (*AppResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*AppReq)(nil), "app.AppReq")
	proto.RegisterType((*AppResp)(nil), "app.AppResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for App service

type AppClient interface {
	Hello(ctx context.Context, in *AppReq, opts ...grpc.CallOption) (*AppResp, error)
}

type appClient struct {
	cc *grpc.ClientConn
}

func NewAppClient(cc *grpc.ClientConn) AppClient {
	return &appClient{cc}
}

func (c *appClient) Hello(ctx context.Context, in *AppReq, opts ...grpc.CallOption) (*AppResp, error) {
	out := new(AppResp)
	err := grpc.Invoke(ctx, "/app.App/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for App service

type AppServer interface {
	Hello(context.Context, *AppReq) (*AppResp, error)
}

func RegisterAppServer(s *grpc.Server, srv AppServer) {
	s.RegisterService(&_App_serviceDesc, srv)
}

func _App_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Hello(ctx, req.(*AppReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _App_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _App_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0x28, 0x50, 0x92, 0xe3, 0x62, 0x73,
	0x2c, 0x28, 0x08, 0x4a, 0x2d, 0x14, 0x12, 0xe1, 0x62, 0xcd, 0x48, 0xcd, 0xc9, 0xc9, 0x97, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0xa4, 0xb9, 0xd8, 0xc1, 0xf2, 0xc5, 0x05, 0x42,
	0x02, 0x5c, 0xcc, 0xb9, 0xc5, 0xe9, 0x50, 0x69, 0x10, 0xd3, 0x48, 0x9b, 0x8b, 0xd9, 0xb1, 0xa0,
	0x40, 0x48, 0x85, 0x8b, 0xd5, 0x03, 0xa4, 0x58, 0x88, 0x5b, 0x2f, 0xb1, 0xa0, 0x40, 0x0f, 0x62,
	0x9e, 0x14, 0x0f, 0x82, 0x53, 0x5c, 0xa0, 0xc4, 0x90, 0xc4, 0x06, 0xb6, 0xd5, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xa0, 0xa0, 0x0b, 0xd3, 0x83, 0x00, 0x00, 0x00,
}
